fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    python: "https://github.com/stankevich/puppet-python.git"
    nodejs: "https://github.com/voxpupuli/puppet-nodejs"
  symlinks:
    jupyterhub: "#{source_dir}"
